### ISSUE TITLE
Not allowed to deploy cluster without controller

### ISSUE THREAD

**Issue by hmntsharma** [openconfig/kne#353]
Hi All,

Is there any way to deploy the cluster without any controllers? Please.
There is no need for it with Cisco XRd images.

```yaml
$ cat kind-bridge.yaml
# kind-bridge.yaml cluster config file sets up a kind cluster where default PTP CNI plugin
# is swapped with the Bridge CNI plugin.
# Bridge CNI plugin is required by some Network OSes to operate.
cluster:
  kind: Kind
  spec:
    name: kne
    recycle: True
    version: v0.17.0
    image: kindest/node:v1.26.0
    config: ../../kind/kind-no-cni.yaml
    additionalManifests:
      - ../../manifests/kind/kind-bridge.yaml
ingress:
  kind: MetalLB
  spec:
    manifest: ../../manifests/metallb/manifest.yaml
    ip_count: 100
cni:
  kind: Meshnet
  spec:
    manifest: ../../manifests/meshnet/grpc/manifest.yaml
```

```
$ kne deploy kind-bridge.yaml
Error: no controllers specified
```

Thanks!
